-- Dreame Products Seed Data
-- Insert all products from product list
-- channel_pricing.brandstore = Retail Price (Harga A / Visibility For Staff)

-- Delete related records first (foreign key constraints)
DELETE FROM stock_opname_items;
DELETE FROM stock_opname;
DELETE FROM purchase_order_items;
DELETE FROM purchase_orders;
DELETE FROM sales;
DELETE FROM inventory;

-- Delete existing products
DELETE FROM products;

INSERT INTO products (sku, name, category, sub_category, channel_pricing, price_retail, is_active)
VALUES
-- ==================== IMAGE 1: Main Unit Products ====================
('SLDMRB0H12SAE', 'H12S AE', 'Main Unit', 'Wet & Dry', '{"brandstore": 3590000}', 3590000, true),
('SLDMRB0H12PR', 'H12 Pro', 'Main Unit', 'Wet & Dry', '{"brandstore": 4990000}', 4990000, true),
('SLDMRB0H12DL', 'H12 Dual', 'Main Unit', 'Wet & Dry', '{"brandstore": 8690000}', 8690000, true),
('SLDRH14WDVCL', 'H14', 'Main Unit', 'Wet & Dry', '{"brandstore": 7190000}', 7190000, true),
('SLDRH14ULTRA', 'H14 Ultra', 'Main Unit', 'Wet & Dry', '{"brandstore": 8690000}', 8690000, true),
('SLDRD9MXGEN2', 'D9Max Gen 2', 'Main Unit', 'Robovac', '{"brandstore": 3250000}', 3250000, true),
('SLDRRVL10PRM', 'L10 Prime', 'Main Unit', 'Robovac', '{"brandstore": 5490000}', 5490000, true),
('SLDRRVL10UTR', 'L10 Ultra', 'Main Unit', 'Robovac', '{"brandstore": 6490000}', 6490000, true),
('SLDRL10SUGE2', 'L10S Ultra Gen 2', 'Main Unit', 'Robovac', '{"brandstore": 8990000}', 8990000, true),
('SLRDL30SURVC', 'L30S Ultra', 'Main Unit', 'Robovac', '{"brandstore": 11990000}', 11990000, true),
('SLDRX40RBVBL', 'X40 Ultra Black', 'Main Unit', 'Robovac', '{"brandstore": 15990000}', 15990000, true),
('SLDRX40RBVWH', 'X40 Ultra White', 'Main Unit', 'Robovac', '{"brandstore": 15990000}', 15990000, true),
('SLDRR10STVC0', 'R10', 'Main Unit', 'Stick Vacuum', '{"brandstore": 2990000}', 2990000, true),
('SLDRR10PRSTV', 'R10 Pro', 'Main Unit', 'Stick Vacuum', '{"brandstore": 4490000}', 4490000, true),
('SLDRR20STVC0', 'R20', 'Main Unit', 'Stick Vacuum', '{"brandstore": 5990000}', 5990000, true),
('SLDRV12SCRVC', 'V12S', 'Main Unit', 'Stick Vacuum', '{"brandstore": 4390000}', 4390000, true),
('SLDRHDGLMPNK', 'Hair Gleam Pink', 'Main Unit', 'Beauty', '{"brandstore": 1190000}', 1190000, true),
('SLDRHDGLMBLE', 'Hair Gleam Blue', 'Main Unit', 'Beauty', '{"brandstore": 1190000}', 1190000, true),
('SLDRHDGLMGRY', 'Hair Gleam Gray', 'Main Unit', 'Beauty', '{"brandstore": 1190000}', 1190000, true),
('SLDEAHDA60WH', 'Hair Glory White', 'Main Unit', 'Beauty', '{"brandstore": 1590000}', 1590000, true),
('SLDEAHDA60RS', 'Hair Glory Rose Gold', 'Main Unit', 'Beauty', '{"brandstore": 1590000}', 1590000, true),
('SLDRIPLHRMPN', 'IPL Hair Removal', 'Main Unit', 'Beauty', '{"brandstore": 3390000}', 3390000, true),
('SLDRDHSHDRSG', 'Pocket Space Gray', 'Main Unit', 'Beauty', '{"brandstore": 2990000}', 2990000, true),
('SLDRDHSHDRTG', 'Pocket Titanium Gold', 'Main Unit', 'Beauty', '{"brandstore": 2990000}', 2990000, true),
('SLDRDAISTYWH', 'Airstyle', 'Main Unit', 'Beauty', '{"brandstore": 3990000}', 3990000, true),
('SLDRDD20PMRM', 'D20 Pro', 'Main Unit', 'Mite Removal', '{"brandstore": 1690000}', 1690000, true),
('SLDRH13FLEXR', 'H13 Flex Reach', 'Main Unit', 'Wet & Dry', '{"brandstore": 6890000}', 6890000, true),
('SLDRX50RBVWH', 'X50 Ultra White', 'Main Unit', 'Robovac', '{"brandstore": 19990000}', 19990000, true),
('SLDRX50RBVBL', 'X50 Ultra Black', 'Main Unit', 'Robovac', '{"brandstore": 19990000}', 19990000, true),
('SLDRV18SAQVC', 'V18S', 'Main Unit', 'Stick Vacuum', '{"brandstore": 6990000}', 6990000, true),
('SLDRG10WDC00', 'G10', 'Main Unit', 'Wet & Dry', '{"brandstore": 2990000}', 2990000, true),
('SLDRD20ULRVC', 'D20 Ultra', 'Main Unit', 'Robovac', '{"brandstore": 7690000}', 7690000, true),
('SLDRZ10SSTVC', 'Z10S Station', 'Main Unit', 'Stick Vacuum', '{"brandstore": 6990000}', 6990000, true),
('SLDRH15PHWDC', 'H15 Pro Heat', 'Main Unit', 'Wet & Dry', '{"brandstore": 11990000}', 11990000, true),
('SLDRH15PROWD', 'H15 Pro', 'Main Unit', 'Wet & Dry', '{"brandstore": 10590000}', 10590000, true),
('SLDRAQ10PRBL', 'Aqua 10 Pro Track (black)', 'Main Unit', 'Robovac', '{"brandstore": 22990000}', 22990000, true),
('SLDRAQ10PRWH', 'Aqua 10 Pro Track (white)', 'Main Unit', 'Robovac', '{"brandstore": 22990000}', 22990000, true),
('SLDRPOUNIROS', 'Pocket Uni-Rose', 'Main Unit', 'Beauty', '{"brandstore": 3290000}', 3290000, true),
('SLDRPOUNITNG', 'Pocket Uni-Titanium', 'Main Unit', 'Beauty', '{"brandstore": 3290000}', 3290000, true),
('SLDRPOUNIGRY', 'Pocket Uni-Grey', 'Main Unit', 'Beauty', '{"brandstore": 3290000}', 3290000, true),
('SLDRPM10AIRP', 'PM10', 'Main Unit', 'Purifier', '{"brandstore": 11990000}', 11990000, true),
('SLDRH12FLEXW', 'H12 Flex Reach', 'Main Unit', 'Wet & Dry', '{"brandstore": 5790000}', 5790000, true),

-- ==================== IMAGE 2: Accessories ====================
('SLDRX50UMBRS', 'Dreame X50 Ultra Main Brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRX50USDBF', 'Dreame X50 Ultra Series Dust Box Filter', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRX50UACCK', 'Dreame X50 Ultra Accessories Kits( Include TroboWave Detangling Brush)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRTHRCLAXK', 'Dreame Threshold Climbing Auxiliary Kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRARAW7WHK', 'RAW7 water hookup kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRX40USDBR', 'X40 ultra side brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRD9MOG2SB', 'Dreame D9 Max / D9 Max Gen 2 Side Brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRH14ORULF', 'Dreame H14 / H14 Ultra Filter', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRH14UBRLR', 'Dreame H14 Ultra Brush Roller', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRD9MG2MOP', 'Dreame D9 Max Gen 2 Mop Pad', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRH14UM500', 'Dreame H14 Ultra Multi-Surface Floor Cleaner (500ml)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRARVHCBV2', 'Hair Cutting Brush 2.0', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRD20PBRFS', 'D20 Pro Mite Remover FilterSponge', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRD20OPBRLR', 'D20 Pro Mite Remover Brush Roller', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRD9MG2KIT', 'D9 Max Gen2 assessories kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAX40ACCK', 'X40ultra assessories kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAX30L10K', 'L30S Ultra Accessories Kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAH12PF00', 'H12 Pro Filter', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAH12PRBR', 'H12 PRO Brush roller', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAMSFCL500', 'Multi-surface floor cleaner (500ML)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRA1600GMH', 'Glory magnetic hanger', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRHDNZ16RS', 'Hair Glory Essence Nozzle', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAMSFCL1L', 'Multi-Surface Floor Cleaner(1L)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRASVSTRFL', 'Silver Ion Sterilizer and Filter kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAR10R20K', 'R10/R10 Pro/R20 accessories kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAR10BR00', 'R10 rolling brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAR1020RB', 'R10 pro/R20 rolling brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAD9MXMOP', 'D9 max mop pad', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAD9MAXKT', 'D9 Max Accessories Kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10BRCV', 'L10s Ultra/L10 Ultra/L10 Prime brush cover', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10USDB', 'L10s Ultra/L10 Ultra dust bag', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10USMP', 'L10s Ultra/L10 ultra Mop pad', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10UACK', 'L10s Ultra/L10 ultra Accessories Kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAR10BTT0', 'R10 battery', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAR20BTT0', 'R20 battery', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAD9MXMBR', 'D9 Max Main Brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10PMBR', 'L10 Prime Main Brush (Rubber Brush)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRASBLCK0', 'Side Brush(Black)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAD9MXDBL0', 'D9 Max Dust Box Filter', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10PBF0', 'L10 Prime Box Filter', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAD9MXWBC', 'D9 Max(White) Brush Cover', 'Accessory', 'Accessory', '{}', 0, true),

-- ==================== IMAGE 3: More Accessories ====================
('SLDRD9MXWFMP', 'D9 Max Wash-free Mop Pad', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10SARC', 'L10s Ultra automatic refill cleaning fluid (300mL) 3 bottles', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10PACK', 'L10 Prime ACC KIT ( 1Main Brush (Rubber) +2Side Brush+2Dust Box Filter)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAGLRYWHT', 'Glory Essence Mouthpiece-White (includes 1 Essence Bullet)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAGLRYGLD', 'Glory Essence Mouthpiece-Frost Feather Gold (includes 1 Essence Bullet)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRD9MXWFMP2', 'Dreame Hair Glory Hair Dryer Holder', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAR10BR002', 'R10 rolling brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAR1020SR', 'R10 pro/R20 rolling brush', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL20UDBF', 'L20 Ultra Dust Box Filter', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL20UMP', 'L20 Ultra Mop Pad', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL20UDCB', 'L20 Ultra Dust Collection Bag', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL20UAFB', 'L20 Ultra Auto-Fill Speciality Cleaning Fluid (450mL)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL20UDCB2', 'L20 Ultra Accessories Kit', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAH12DBRR', 'H12 DUAL Brush roller', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAH12DFLTR', 'H12 DUAL Filter', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAHGSMZNZ', 'Dreame High Speed Hair Gleam smooth nozzle', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAL10PRDB8', 'L10s Pro Ultra/X30 Ultra Dust Bag RDB8', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAH15PHFC', 'Free gift: 500ML High-Temperature Multi-Surface Floor Cleaner HFF5', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAX30RDB8', 'Set RDB8', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRPTBLCOMB', 'COMB', 'Accessory', 'Accessory', '{"brandstore": 169000}', 169000, true),
('SLDRAZ10SBAG', 'SET DUST BAG Z10S', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAMSFCL1L2', 'FREE Multi-Surface Floor Cleaner(1L)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAAQ10KIT', 'Accessories Kit Aqua 10', 'Accessory', 'Accessory', '{"brandstore": 1490000}', 1490000, true),
('SLDRMINIWHIT', 'Hair Mini White', 'Main Unit', 'Beauty', '{"brandstore": 990000}', 990000, true),
('SLDRMINIPIN K', 'Hair Mini Pink', 'Main Unit', 'Beauty', '{"brandstore": 990000}', 990000, true),
('SLDRMINIBLUE', 'Hair Mini Blue', 'Main Unit', 'Beauty', '{"brandstore": 990000}', 990000, true),
('SLDRMINIGREN', 'Hair Mini Green', 'Main Unit', 'Beauty', '{"brandstore": 990000}', 990000, true),
('SLDRBAG500MM', 'Dreame Gift Bag 500*150*400mm', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRADRBYTCS', 'Dreame Boy Art Toy Classic Series (full set)', 'Accessory', 'Accessory', '{"brandstore": 350000}', 350000, true),
('SLDRBAG250MM', 'Dreame Gift Bag 250mm', 'Accessory', 'Accessory', '{}', 0, true),
('DEMO-SLDRAPOCK', 'Pocket rack display', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRPOUNIROS2', 'FREE Pocket Uni-Rose', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRPOUNITNG2', 'FREE Pocket Uni-Titanium', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRPOUNIGRY2', 'FREE Pocket Uni-Grey', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRAAQ10KIT2', 'FREE Accessories Kit Aqua 10', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRL10GE3WH', 'L10S Ultra GEN 3 (White)', 'Main Unit', 'Robovac', '{"brandstore": 11990000}', 11990000, true),
('SLDRL10GE3BL', 'L10S Ultra GEN 3 (Black)', 'Main Unit', 'Robovac', '{"brandstore": 11990000}', 11990000, true),
('SLDRAH13FSTC', 'FREE Water Tank Deodorant Stick HDEM2', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAUMBRLBL', 'DREAME UMBRELLA', 'Accessory', 'Accessory', '{"brandstore": 500000}', 500000, true),
('SLDRTMBLR', 'DREAME TUMBLR', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRHDGLMPNK2', 'FREE Hair Gleam Pink', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRHDGLMBLE2', 'FREE Hair Gleam Blue', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRHDGLMGRY2', 'FREE Hair Gleam Gray', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRAKIRAK80', 'FREE Dreame L10S Ultra GEN3 ACC KIT RAK80', 'Main Unit', 'Robovac', '{"brandstore": 0}', 0, true),

-- ==================== IMAGE 4: More Products ====================
('SLDRADBARDB1', 'Automatic Cleaning Solution Dispenser Module ARDB1', 'Accessory', 'Accessory', '{"brandstore": 459000}', 459000, true),
('SLDRADBARDB12', 'FREE Automatic Cleaning Solution Dispenser Module ARDB1', 'Accessory', 'Accessory', '{}', 0, true),
('SLDR10ROLLBL', 'Aqua 10 Roller (Black)', 'Main Unit', 'Robovac', '{"brandstore": 17990000}', 17990000, true),
('SLDR10ROLLWH', 'Aqua 10 Roller (White)', 'Main Unit', 'Robovac', '{"brandstore": 17990000}', 17990000, true),
('SLDRH15PFOAM', 'H15 Pro FoamWash', 'Main Unit', 'Wet & Dry', '{"brandstore": 10990000}', 10990000, true),
('SLDRN20CARPC', 'N20 Steam', 'Main Unit', 'Steam Cleaner', '{"brandstore": 3590000}', 3590000, true),
('SLDRH13SFLEX', 'H13S FLEX REACH', 'Main Unit', 'Wet & Dry', '{"brandstore": 6890000}', 6890000, true),
('SLDRMINIWHIT2', 'FREE Hair Mini White', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRMINIPIN K2', 'FREE Hair Mini Pink', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRMINIBLUE2', 'FREE Hair Mini Blue', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRMINIGREN2', 'FREE Hair Mini Green', 'Main Unit', 'Beauty', '{"brandstore": 0}', 0, true),
('SLDRDD20PMRM2', 'FREE D20 Pro', 'Main Unit', 'Mite Removal', '{"brandstore": 0}', 0, true),
('SLDRL10GE3WH2', 'FREE L10S Ultra GEN 3 (White)', 'Main Unit', 'Robovac', '{"brandstore": 0}', 0, true),
('SLDRL10GE3BL2', 'FREE L10S Ultra GEN 3 (Black)', 'Main Unit', 'Robovac', '{"brandstore": 0}', 0, true),
('SLDRAH15PHFC2', 'High-Temperature Multi-Surface Floor Cleaner HFF5', 'Accessory', 'Accessory', '{"brandstore": 319000}', 319000, true),
('SLDRAFOAMFCL', 'Free gift:500ML Dreame Foaming Floor Cleaner HFF7', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAN20HNF5', 'FREE Dreame N20 Steam Portable Carpet Spot Cleaner HNF5 (1L)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAFOAMFCL2', 'Dreame Foaming Floor Cleaner HFF7 (500mL)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAN20HNF52', 'Dreame N20 Steam Portable Carpet Spot Cleaner HNF5 (1L)', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRR10STVC02', 'FREE R10', 'Main Unit', 'Stick Vacuum', '{"brandstore": 0}', 0, true),
('SLDRARBG23BC', 'RBG23 Brush Cover Black for X50 Series', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRPTBLCOMB2', 'FREE COMB', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAKIRAK67', 'Dreame Aqua 10 Roller ACC KIT RAK67', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAKIRAK672', 'FREE Dreame Aqua 10 Roller ACC KIT RAK67', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAQUAFILT', 'Dreame Aqua 10 Dust Box Filter RHF22', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAIRFPT60', 'PT60-Black', 'Main Unit', 'Small Appliances', '{}', 0, true),
('SLDRH16PRSTM', 'H16 Pro Steam', 'Main Unit', 'Wet & Dry', '{}', 0, true),
('SLDRH12GTWET', 'H12GT', 'Main Unit', 'Wet & Dry', '{}', 0, true),
('SLDRF20RBVBL', 'F20 Black', 'Main Unit', 'Robovac', '{}', 0, true),
('SLDRAPETSLTN', 'Dreame Pet Odor Solution AWH15', 'Accessory', 'Accessory', '{}', 0, true),
('SLDRAPETSLTN2', 'FREE Dreame Pet Odor Solution AWH15', 'Accessory', 'Accessory', '{}', 0, true)

ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  sub_category = EXCLUDED.sub_category,
  channel_pricing = EXCLUDED.channel_pricing,
  updated_at = NOW();
